#!/usr/bin/env python3
"""Merge reviewed coordinates into data/place_coordinates_seed.csv.

Accepted inputs:
- data/place_coordinates_custom.csv exported from the browser backlog view
- data/place_geocoding_review.csv generated by scripts/geocode_places.py

The graph builder reads place_coordinates_seed.csv by CanonicalName.
"""
from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
SEED = DATA / "place_coordinates_seed.csv"
CUSTOM = DATA / "place_coordinates_custom.csv"
REVIEW = DATA / "place_geocoding_review.csv"


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def has_coord(row: dict[str, str]) -> bool:
    return bool(str(row.get("Latitude", "")).strip() and str(row.get("Longitude", "")).strip())


def key_name(row: dict[str, str]) -> str:
    return (row.get("CanonicalName") or row.get("Place") or "").strip()


def accepted_review(row: dict[str, str]) -> bool:
    status = str(row.get("Status") or row.get("CoordinateStatus") or "").strip().lower()
    return status in {"approved", "manual_approved", "candidate_approved", "exact_manual", "approximate_manual"}


def main() -> None:
    seed_rows = read_csv(SEED)
    by_name = {key_name(r): dict(r) for r in seed_rows if key_name(r)}
    updates = 0

    for row in read_csv(CUSTOM):
        name = key_name(row)
        if not name or not has_coord(row):
            continue
        by_name[name] = {
            "CanonicalName": name,
            "Latitude": row["Latitude"].strip(),
            "Longitude": row["Longitude"].strip(),
            "CoordinateStatus": row.get("CoordinateConfidence") or "manual_approved",
            "CoordinateNotes": "; ".join(x for x in [row.get("Source", ""), row.get("Notes", "")] if x),
        }
        updates += 1

    for row in read_csv(REVIEW):
        name = key_name(row)
        if not name or not has_coord(row) or not accepted_review(row):
            continue
        by_name[name] = {
            "CanonicalName": name,
            "Latitude": row["Latitude"].strip(),
            "Longitude": row["Longitude"].strip(),
            "CoordinateStatus": row.get("CoordinateStatus") or row.get("Status") or "approved",
            "CoordinateNotes": row.get("CoordinateNotes") or row.get("Notes") or "approved geocoding review",
        }
        updates += 1

    fields = ["CanonicalName", "Latitude", "Longitude", "CoordinateStatus", "CoordinateNotes"]
    with SEED.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for name in sorted(by_name):
            writer.writerow({k: by_name[name].get(k, "") for k in fields})
    print(f"Merged {updates} coordinate updates into {SEED}.")
    print("Next: python scripts/build_graph.py && python scripts/validate_graph.py")


if __name__ == "__main__":
    main()
